name: "Continuous Integration"

on:
  pull_request:
    branches:
      - "*.x"
    paths:
      - .github/workflows/continuous-integration.yml
      - composer.*
      - src/**
      - phpunit.xml.dist
      - test_fixtures/**
      - tests/**
  push:
    branches:
      - "*.x"
    paths:
      - .github/workflows/continuous-integration.yml
      - composer.*
      - src/**
      - phpunit.xml.dist
      - test_fixtures/**
      - tests/**

jobs:
  phpunit:
    name: "PHPUnit"
    uses: "doctrine/.github/.github/workflows/continuous-integration.yml@7.1.0"
    with:
      php-versions: '["8.1", "8.2", "8.3"]'
